name: "GChat notifier"
description: "Notify of new deployments via Google Chat"
inputs:
  project-name: # Name of the project
    description: "Name of the project"
    required: true
  sheed-id: # URL of the sheet
    description: "URL of the sheet"
    required: true
  service-account-email: # E-mail of the service account
    description: "E-mail of the service account"
    required: true
  service-account-private-key: # Private key of the GCP service account
    description: "Private key of the GCP service account"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
